vim.keymap.set("n", "<Esc>", "<cmd>nohlsearch<CR>")
vim.api.nvim_set_keymap('n', '<C-e>', '5<C-e>', {noremap = true})
vim.api.nvim_set_keymap('n', '<C-y>', '5<C-y>', {noremap = true})
vim.api.nvim_set_keymap('i', '<C-BS>', '<C-W>', {noremap = true})
vim.api.nvim_set_keymap('n', '<C-h>', '<cmd>tabm -1<CR>', {noremap = true})
vim.api.nvim_set_keymap('n', '<C-l>', '<cmd>tabm +1<CR>', {noremap = true})
vim.api.nvim_set_keymap('n', '<A-j>', '<cmd>tabprevious<CR>', {noremap = true})
vim.api.nvim_set_keymap('n', '<A-k>', '<cmd>tabnext<CR>', {noremap = true})
vim.api.nvim_set_keymap('', '<C-n>', '<cmd>NvimTreeToggle<CR>', {noremap = true})
vim.api.nvim_set_keymap('', '<C-t>', '<cmd>FloatermNew --name=myfloat --height=0.8 --width=0.7 --autoclose=2 <CR>', {noremap = true})
vim.api.nvim_set_keymap('', '<A-t>', '<cmd>FloatermToggle myfloat<CR>', {noremap = true})
vim.api.nvim_set_keymap('t', '<A-t>', '<C-\\><C-n> <cmd>FloatermToggle myfloat', {noremap = true})
vim.api.nvim_set_keymap('t', '<A-n>', '<C-\\><C-n> <cmd>FloatermNext', {noremap = true})
vim.api.nvim_set_keymap('n', '<S-j>', '5j', {noremap = true})
vim.api.nvim_set_keymap('n', '<S-k>', '5k', {noremap = true})
vim.api.nvim_set_keymap('v', '<S-j>', '5j', {noremap = true})
vim.api.nvim_set_keymap('v', '<S-k>', '5k', {noremap = true})
vim.api.nvim_set_keymap('n', '<S-h>', 'b', {noremap = true})
vim.api.nvim_set_keymap('n', '<S-l>', 'w', {noremap = true})
vim.api.nvim_set_keymap('v', '<S-h>', 'b', {noremap = true})
vim.api.nvim_set_keymap('v', '<S-l>', 'w', {noremap = true})
vim.api.nvim_set_keymap('n', '<C-S-j>', '<cmd>m .+1<CR>==', {noremap = true})
vim.api.nvim_set_keymap('n', '<C-S-k>', '<cmd>m .-2<CR>==', {noremap = true})
vim.api.nvim_set_keymap('i', '<C-S-k>', '<Esc><cmd>m .-2<CR>==gi', {noremap = true})
vim.api.nvim_set_keymap('i', '<C-S-j>', '<Esc><cmd>m .+1<CR>==gi', {noremap = true})
vim.api.nvim_set_keymap('v', '<C-S-j>', '<cmd>m \'>+1<CR>gv=gv', {noremap = true})
vim.api.nvim_set_keymap('v', '<C-S-k>', '<cmd>m \'<-2<CR>gv=gv', {noremap = true})
vim.api.nvim_set_keymap('', '<C-m>', '<cmd>MarkdownPreviewToggle', {noremap = true})
vim.api.nvim_set_keymap('', '<Leader>lp', '<cmd>lclose<CR>', {noremap = true})
vim.api.nvim_set_keymap('', '<Leader>ll', '<cmd>lopen<CR>', {noremap = true})
vim.api.nvim_set_keymap('', '<Leader>tm', '<cmd>TableModeToggle<CR>', {noremap = true})
vim.api.nvim_set_keymap('', '<Leader>st', '<cmd>ALEToggle<CR>', {noremap = true})
vim.api.nvim_set_keymap('', '<Leader>nn', '<cmd>lnext<CR>', {noremap = true})
vim.api.nvim_set_keymap('', '<Leader>pp', '<cmd>lprevious<CR>', {noremap = true})
vim.api.nvim_set_keymap('', '<Leader>ft', '<cmd>RustFmt<CR>', {noremap = true})
vim.api.nvim_set_keymap('', '<Leader>b', '<cmd>DapToggleBreakpoint<CR>', {noremap = true})
vim.api.nvim_set_keymap('', '<Leader>c', '<cmd>lua require\'dap\'.clear_breakpoints()<CR>', {noremap = true})
vim.api.nvim_set_keymap('n', '<Leader>zn', '<cmd>TZNarrow<CR>', {noremap = true})
vim.api.nvim_set_keymap('v', '<Leader>zn', '<cmd>\'<,\'>TZNarrow<CR>', {noremap = true})
vim.api.nvim_set_keymap('n', '<leader>zf', '<cmd>TZFocus<CR>', {noremap = true})
vim.api.nvim_set_keymap('n', '<leader>zm', '<cmd>TZMinimalist<CR>', {noremap = true})
vim.api.nvim_set_keymap('n', '<leader>zz', '<cmd>TZAtaraxis<CR>', {noremap = true})
vim.api.nvim_set_keymap('', '<Leader>no', '<cmd>Neorg workspace notes<CR>', {noremap = true})
vim.api.nvim_set_keymap('', '<Leader>nr', '<cmd>Neorg return<CR>', {noremap = true})
vim.api.nvim_set_keymap('', '<Leader>nc', '<cmd>Neorg keybind all core.looking-glass.magnify-code-block<CR>', {noremap = true})
vim.api.nvim_set_keymap('', '<F5>', '<cmd>DapContinue<CR>', {noremap = true})
vim.api.nvim_set_keymap('', '<F10>', '<cmd>DapStepOver<CR>', {noremap = true})
vim.api.nvim_set_keymap('', '<F11>', '<cmd>DapStepInto<CR>', {noremap = true})
vim.api.nvim_set_keymap('', '<F12>', '<cmd>DapStepOut<CR>', {noremap = true})
vim.api.nvim_set_keymap('n', '<leader>ff', '<cmd>Telescope find_files<cr>', {noremap = true})
vim.api.nvim_set_keymap('n', '<leader>fg', '<cmd>Telescope live_grep<cr>', {noremap = true})
vim.api.nvim_set_keymap('n', '<leader>fb', '<cmd>Telescope buffers<cr>', {noremap = true})
vim.api.nvim_set_keymap('n', '<leader>fn', '<cmd>Telescope treesitter<cr>', {noremap = true})
vim.api.nvim_set_keymap('n', '<leader>fh', '<cmd>TodoTelescope<cr>', {noremap = true})
vim.api.nvim_set_keymap('i', '<expr>', "<Tab>   vsnip#jumpable(1)   ? '<Plug>(vsnip-jump-next)'      : '<Tab>'", {noremap = true})
vim.api.nvim_set_keymap('s', '<expr>', "<Tab>   vsnip#jumpable(1)   ? '<Plug>(vsnip-jump-next)'      : '<Tab>'", {noremap = true})
vim.api.nvim_set_keymap('i', '<expr>', "<S-Tab> vsnip#jumpable(-1)  ? '<Plug>(vsnip-jump-prev)'      : '<S-Tab>'", {noremap = true})
vim.api.nvim_set_keymap('s', '<expr>', "<S-Tab> vsnip#jumpable(-1)  ? '<Plug>(vsnip-jump-prev)'      : '<S-Tab>'", {noremap = true})
