#!/bin/bash

if [ $1 ]; then
    LINE=$@
else
    LINE="more stuff"
fi

rm -rf Pictures/backgrounds .local .config .themes .icons kanagawa-theme 

cp ~/.bashrc .
cp ~/.bash_profile .
cp ~/.nvimrc .
cp ~/Pictures/backgrounds/ . -r
cp ~/.gitconfig .
cp ~/.local/bin/tools/ .local/bin/ -r
cp ~/.local/source .local/ -r
cp ~/.config/dunst/ .config -r
cp ~/.config/nvim/ .config -r
cp ~/.config/hypr/ .config -r
cp ~/.config/waybar/ .config -r
cp ~/.config/rofi/ .config -r
cp ~/.config/kitty/ .config -r
cp ~/.config/gtk-4.0/ .config -r
cp ~/.config/starship.toml .config -r
cp ~/.themes . -r
cp ~/.icons . -r
cp ~/.config/fastfetch/ .config -r
cp ~/kanagawa-theme/ . -r

git add -A
git commit -m "$LINE"
git push origin master
