#!/bin/bash

if [ $1 ]; then
    LINE=$@
else
    LINE="more stuff"
fi

rm -rf .local .config .themes .icons kanagawa-theme
mkdir .local/bin -p
mkdir .config

cp ~/.bashrc .
cp ~/.inputrc .
cp ~/.bash_profile .
cp ~/.gitconfig .
cp ~/.tmux.conf .
cp ~/.local/bin/tools/ .local/bin/ -r
cp ~/.config/dunst/ .config -r
cp ~/.config/hypr/ .config -r
cp ~/.config/jj/ .config -r
cp ~/.config/waybar/ .config -r
cp ~/.config/rofi/ .config -r
cp ~/.config/alacritty/ .config -r
cp ~/.config/starship.toml .config -r
cp ~/.themes . -r
cp ~/.icons . -r
cp ~/kanagawa-theme/ . -r

rsync -a ~/.config/nvim .config/ --exclude lazy-lock.json

git add -A
git commit -m "$LINE"
git push origin master
