[general]
import = ["kanagawa.toml"]

[window]
padding = { x = 3 }

[font]
normal = {family = "JetBrainsMono NFM", style=""}
bold = {family = "JetBrainsMono NFM", style="Bold"}
italic = {family = "JetBrainsMono NFM", style = "Italic"}
bold_italic = {family = "JetBrainsMono NFM", style = "Bold Italic"}
size = 9.9

[cursor]
style = { shape = "Beam", blinking = "On" }
blink_interval = 500
